on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
      - run: dotnet run --project targets --no-launch-profile
      - name: publish
        if: github.event.release != null
        env:
          API_KEY: ${{ secrets.NUGET_RAPHA_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ env.API_KEY }}
