on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]
env:
  DOTNET_NOLOGO: true
permissions: {}
jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      statuses: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4
      - run: dotnet run --project targets --no-launch-profile
      - name: publish
        if: github.event.release != null
        env:
          API_KEY: ${{ secrets.NUGET_RAPHA_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ env.API_KEY }}
