on:
  push:
    branches: [main, release-*]
    tags: ["*.*.*"]
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: setup-dotnet 7.0.306
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.306"
      - run: dotnet --info
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./build.cmd
