on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]
env:
  DOTNET_NOLOGO: true
permissions: {}
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      statuses: write
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      - run: dotnet run --project targets --no-launch-profile
      - name: publish
        if: github.event.release != null
        env:
          API_KEY: ${{ secrets.NUGET_RAPHA_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ env.API_KEY }}
