on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]
env:
  DOTNET_NOLOGO: true
permissions: {}
jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
      statuses: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
      - run: dotnet run --project targets --no-launch-profile
      - name: publish
        if: github.event.release != null && matrix.os == 'windows-2022'
        env:
          API_KEY: ${{ secrets.NUGET_RAPHA_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ env.API_KEY }}
