on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: github/super-linter/slim@v5
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\.g\.cs$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
