on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter@v5
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\.g\.cs$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
