on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2
      - uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\.g\.cs$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
