on:
  pull_request:
  push:
    branches: [main]
permissions: {}
jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@4e51915f4a812abf59fed160bb14595c0a38a9e7 # v6
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\.g\.cs$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
