on:
  pull_request:
  push:
    branches: [main]
permissions: {}
jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\.g\.cs$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
