on:
  pull_request:
  push:
    branches: [main]
permissions: {}
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: npx cspell@6 "**/*"
