on:
  pull_request:
  push:
    branches: [main]
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: npx cspell@6 "**/*"
