on:
  pull_request:
  push:
    branches: [main]
permissions: {}
jobs:
  spell-check:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: npx cspell@6 "**/*"
